---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: digitalocean-token
  namespace: gloo-mesh
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-parameterstore
    kind: SecretStore
  target:
    name: digitalocean-token
    creationPolicy: Owner
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: digitalocean-token
    secretKey: digitalocean-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: gloo-mesh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
  namespace: gloo-mesh
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"] 
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: gloo-mesh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: gloo-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.13.1
        args:
        - --events
        - --policy=upsert-only
        - --source=service
        - --provider=digitalocean
        env:
        - name: DO_TOKEN
          valueFrom:
            secretKeyRef:
              key: digitalocean-token
              name: digitalocean-token
              optional: false
