---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-parameterstore
  namespace: gloo-mesh
spec:
  provider:
    aws:
      region: us-east-1
      service: ParameterStore
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: license-keys
  namespace: gloo-mesh
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-parameterstore
    kind: SecretStore
  target:
    name: license-keys
    creationPolicy: Owner
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: gloo-gateway-license-key
    secretKey: gloo-gateway-license-key
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: gloo-mesh-license-key
    secretKey: gloo-mesh-license-key
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: gloo-network-license-key
    secretKey: gloo-network-license-key
