---
apiVersion: v1
data: {}
immutable: false
kind: Secret
metadata:
  name: license-keys
  namespace: gloo-mesh
type: Opaque
---
apiVersion: v1
data: {}
immutable: false
kind: Secret
metadata:
  name: digitalocean-token
  namespace: gloo-mesh
type: Opaque
---
