---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-parameterstore
  namespace: gloo-mesh
spec:
  provider:
    aws:
      region: us-east-1
      service: ParameterStore
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: relay-identity-token-secret
  namespace: gloo-mesh
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-parameterstore
    kind: SecretStore
  target:
    name: relay-identity-token-secret
    creationPolicy: Owner
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ .Values.tokenSecretName }}
    secretKey: token 
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: relay-root-tls-secret
  namespace: gloo-mesh
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-parameterstore
    kind: SecretStore
  target:
    name: relay-root-tls-secret
    creationPolicy: Owner
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ .Values.caSecretName }}
    secretKey: ca.crt
