---
apiVersion: v1
data: {}
immutable: false
kind: Secret
metadata:
  name: relay-identity-token-secret
  namespace: gloo-mesh
type: Opaque
---
apiVersion: v1
data: {}
immutable: false
kind: Secret
metadata:
  name: relay-root-tls-secret
  namespace: gloo-mesh
type: Opaque
