---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-parameterstore
  namespace: istio-ingress
spec:
  provider:
    aws:
      region: us-east-1
      service: ParameterStore
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: digitalocean-token
  namespace: istio-ingress
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-parameterstore
    kind: SecretStore
  target:
    name: digitalocean-token
    creationPolicy: Owner
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: digitalocean-token
    secretKey: digitalocean-token
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: istio-ingress
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: jason.skrzypek@solo.io
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-prod-pk 
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-token
            key: digitalocean-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  secretName: istio-ingress-certs
  issuerRef:
    name: letsencrypt-prod
  commonName: "*.{{ .Values.client }}"
  dnsNames:
  - '*.{{ .Values.client }}'
