---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-ca
  namespace: gloo-mesh
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: aws-parameterstore
      kind: SecretStore
  selector:
    secret:
      name: relay-root-tls-secret
  data:
    - match:
        secretKey: ca.crt
        remoteRef:
          remoteKey: "{{ .Values.caSecretName }}"
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret-token 
  namespace: gloo-mesh
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: aws-parameterstore
      kind: SecretStore
  selector:
    secret:
      name: relay-identity-token-secret
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: "{{ .Values.tokenSecretName }}"
