apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: es
  namespace: fleet-default
spec:
  branch: master
  clientSecretName: auth-q7npb
  forceSyncGeneration: 7
  insecureSkipTLSVerify: false
  paths:
  - /shared/external-secrets-operator
  paused: false
  repo: git@github.com:shpwrck/gloo-mesh-example.git
  targets:
  - clusterGroup: gloo-mesh-shared