apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: gma
  namespace: fleet-default
spec:
  branch: master
  clientSecretName: auth-q7npb
  forceSyncGeneration: 11
  insecureSkipTLSVerify: false
  paths:
  - /agent/gloo-mesh-agent
  paused: false
  repo: git@github.com:shpwrck/gloo-mesh-example.git
  targets:
  - clusterGroup: gloo-mesh-agent