apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: post-gme
  namespace: fleet-default
spec:
  branch: master
  clientSecretName: auth-q7npb
  forceSyncGeneration: 9
  insecureSkipTLSVerify: false
  paths:
  - /manager/postrequisite-resources
  paused: false
  repo: git@github.com:shpwrck/gloo-mesh-example.git
  targets:
  - clusterGroup: gloo-mesh-manager